---
title: "Effective Scientific Communication"
description: "Reflecting on Jeffrey Leek's thoughts and my experiences with giving scientific talks."

date: 03-25-2025
categories: [Reflection] 

draft: false 
---

In October of 2024, I gave a presentation as a part of the [Neural Engineering Center Seminar Series](https://case.edu/nec/seminars) at Case Western Reserve University regarding my research topic and current progress. Entitled "Recovery at Home: How Wearable Sensors can Enhance Stroke Rehabilitation" (a title that suspiciously looks generated by ChatGPT), I covered how leveraging wearable technology can help streamline and improve the stroke rehabilitation process. Preparing for this talk consumed my life for the month leading up to it, causing me to neglect schoolwork, but it certainly taught me a lesson about priorities in a Ph.D. graduate program.

In spite of the hours of sleep lost, I look back fondly upon this time. I typically enjoy giving presentations and being in front of crowds. As someone who is no stranger to being on stage as a drummer most of my life, being the center of attention while sharing something I am passionate about is largely a positive experience. However, this talk was arguably the highest-stakes one I would have ever given at that point in my life, so I did feel some pressure to perform optimally. Faculty from all areas of neural engineering would be there listening to me and asking follow-up questions and I, who has a fraction of the experience in the field as they do, would have to hold my own.

My advisor, [Dr. Chris Pulliam](https://case.edu/bme/people/primary-faculty/christopher-pulliam), did a great job preparing me and shaping my presentation into an effective an engaging 45 minutes. As barely a second-year student in the program, I did not have as much data to present as more senior students. As a result, we framed the talk around *communicating the problem* and making sure the audience left the room understanding *why* I am doing the research I am undertaking. Motivating the purpose and incorporating some preliminary data makes for a substantially more engaging and thought-provoking experience.

While reading through Jeffrey Leek's *How to be a Modern Scientist*, his section on "Scientific Talks" really resonated with my philosophy on presentations. Moreover, it reassured me that my approach to my October talk was wise, while also giving me ideas for the next one. Here are some points that want to highlight:

## *"Entertain, don't teach."*

This refrain is repeated again and again during this section of the book, and rightly so. My audience was arriving to campus at 9:00 AM to hear me talk about something that may have nothing to do with their work. For that reason, I needed to put on a show. I needed to speak eloquently and passionately and convey my excitement for my work as effectively as possible. My tone was perhaps too colloquial in retrospect, but I would rather err to folksy and approachable than dry and stuffy.

## "*When presenting results, make sure you are telling a story."*

"Telling a story" was the main approach to this presentation. The entire point was to give a why/how relationship to my research. I made sure to explain where the state of the field was, where it came from, and where I intend to take it in the future. My results section, albeit sparse due to my relative lack of data, fit into this framework. I showed that wearable devices do have potential to quantify the movement of stroke patients in a way that can assess quality of movement, and therefore, quality of recovery.

## "*Say 'I don't know' if you don't know."*

Thankfully, I was already aware of this by the time my talk concluded, or else I would've been *very* nervous for the Q/A section. I did a decent job coming up with "educated guesses" to the questions that I was not sure about (thanks to my experience during the qualifying exams at CWRU), but when I hit a wall, I made sure to admit it. Humbly stating things like "that is something to look into" or "I have not investigated that yet" is a perfectly fine concession in most cases, and makes you appear as a modest and honest researcher.

In all, reflecting on my experience and reading *How to be a Modern Scientist* made me think more critically about my presentation style, thankfully in a mostly positive way. Leek also recommends posting the presentation publicly (which I have not done), among other things that i will incorporate for the next one. In the end, more repetitions of being in front of well-informed audiences and giving scientific talks will only make a more effective communicator, researcher, and overall scientist.
